ALTER TABLE Customer CHANGE Address Addr char(50);
--also
ALTER TABLE Customer RENAME COLUMN Address TO Addr;

USE database_name;
COMMIT;
ROLLBACK;

ALTER TABLE EMPLOYEES DROP CONSTRAINT EMPLOYEES_PK;

ALTER TABLE EMPLOYEES DROP PRIMARY KEY;


