START TRANSACTION
COMMIT
ROLLBACK

START TRANSACTION;

START TRANSACTION;
INSERT INTO student (name, lastname) VALUES ('hem', 'B');
COMMIT;

START TRANSACTION;
INSERT INTO student (name, lastname) VALUES ('hem', 'B');
ROLLBACK;